name: sqlpage-app
services:
  - name: web
    github:
      repo: Rooney-tech/SQL-Database-Project
      branch: main
    dockerfile_path: Dockerfile
    run_command: sqlpage
    environment_slug: docker
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: postgres://avnadmin:AVNS_8rpNm2zZ2hK5zp_ov8o@pg-25309505-odagorooney6-1.f.aivencloud.com:25438/portfolio?sslmode=require
        type: GENERAL